// Cards storage
const cards = {
    "0": {
        name: "The Fool",
        meaning: "Beginnings, possibilities, impulsiveness, innocence, a free spirit",
        td: "\\TD\\TD(0).jpg",
        rw: "\\RW\\RW(0).png",
        ls: " \\LS\\LS(0).png",
    },
    "1": {
        name: "The Magician",
        meaning: "Originality, self-confidence, skill, a breakthrough, resourcefulness",
        td: "\\TD\\TD(1).jpg",
        rw: "\\RW\\RW(1).png",
        ls: " \\LS\\LS(1).png",
    },
    "2": {
        name: "The High Priestess",
        meaning: "Wisdom, intuition, dreams, meandering, an enigma",
        td: "\\TD\\TD(2).jpg",
        rw: "\\RW\\RW(2).png",
        ls: " \\LS\\LS(2).png",
    },
    "3": {
        name: "The Empress",
        meaning: "Fertility, nurturing, accomplishment, nature, abundance",
        td: "\\TD\\TD(3).jpg",
        rw: "\\RW\\RW(3).png",
        ls: " \\LS\\LS(3).png",
    },
    "4": {
        name: "The Emperor",
        meaning: "Stability, leadership, bravery, bold action, structure",
        td: "\\TD\\TD(4).jpg",
        rw: "\\RW\\RW(4).png",
        ls: " \\LS\\LS(4).png",
    },
    "5": {
        name: "The Hierophant",
        meaning: "Conformity, compassion, social approval, tradition, legacy",
        td: "\\TD\\TD(5).jpg",
        rw: "\\RW\\RW(5).png",
        ls: " \\LS\\LS(5).png",
    },
    "6": {
        name: "The Lovers",
        meaning: "Love, harmony, trust, a leap of faith, choice",
        td: "\\TD\\TD(6).jpg",
        rw: "\\RW\\RW(6).png",
        ls: " \\LS\\LS(6).png",
    },
    "7": {
        name: "The Chariot",
        meaning: "A journey, perseverance, rushed decisions, vengeance, victory",
        td: "\\TD\\TD(7).jpg",
        rw: "\\RW\\RW(7).png",
        ls: " \\LS\\LS(7).png",
    },
    "8": {
        name: "Strength",
        meaning: "Courage, conviction, control, determination, patience",
        td: "\\TD\\TD(8).jpg",
        rw: "\\RW\\RW(8).png",
        ls: " \\LS\\LS(8).png",
    },
    "9": {
        name: "The Hermit",
        meaning: "Introspection, withdrawal, prudence, insight, meditation",
        td: "\\TD\\TD(9).jpg",
        rw: "\\RW\\RW(9).png",
        ls: " \\LS\\LS(9).png",
    },
    "10": {
        name: "Wheel of Fortune",
        meaning: "Fortune, an unexpected windfall, karma, destiny, cycles",
        td: "\\TD\\TD(10).jpg",
        rw: "\\RW\\RW(10).png",
        ls: " \\LS\\LS(10).png",
    },
    "11": {
        name: "Justice",
        meaning: "Harmony, balance, equality, virtue, honor",
        td: "\\TD\\TD(11).jpg",
        rw: "\\RW\\RW(11).png",
        ls: " \\LS\\LS(11).png",
    },
    "12": {
        name: "The Hanged Man",
        meaning: "Suspension, restriction, sacrifice, readjustment, improvement",
        td: "\\TD\\TD(12).jpg",
        rw: "\\RW\\RW(12).png",
        ls: " \\LS\\LS(12).png",
    },
    "13": {
        name: "Death",
        meaning: "Metamorphosis, evolution, loss, transition, change",
        td: "\\TD\\TD(13).jpg",
        rw: "\\RW\\RW(13).png",
        ls: " \\LS\\LS(13).png",
    },
    "14": {
        name: "Temperance",
        meaning: "Moderation, harmony, purpose, good influence, reconciliation",
        td: "\\TD\\TD(14).jpg",
        rw: "\\RW\\RW(14).png",
        ls: " \\LS\\LS(14).png",
    },
    "15": {
        name: "The Devil",
        meaning: "Greed, controversy, violence, strange experiences, addiction",
        td: "\\TD\\TD(15).jpg",
        rw: "\\RW\\RW(15).png",
        ls: " \\LS\\LS(15).png",
    },
    "16": {
        name: "The Tower",
        meaning: "Massive change, upheaval, catastrophe, rebuilding, revelation",
        td: "\\TD\\TD(16).jpg",
        rw: "\\RW\\RW(16).png",
        ls: " \\LS\\LS(16).png",
    },
    "17": {
        name: "The Star",
        meaning: "Hope, serenity, inspiration , insight, spirituality",
        td: "\\TD\\TD(17).jpg",
        rw: "\\RW\\RW(17).png",
        ls: " \\LS\\LS(17).png",
    },
    "18": {
        name: "The Moon",
        meaning: "Trickery, melancholy, anguish , illusion, insecurity",
        td: "\\TD\\TD(18).jpg",
        rw: "\\RW\\RW(18).png",
        ls: " \\LS\\LS(18).png",
    },
    "19": {
        name: "The Sun",
        meaning: "Satisfaction, accomplishment, joy, luck, vitality",
        td: "\\TD\\TD(19).jpg",
        rw: "\\RW\\RW(19).png",
        ls: " \\LS\\LS(19).png",
    },
    "20": {
        name: "Judgement",
        meaning: "Improvement, forgiveness, a change of perspective, absolution, rebirth",
        td: "\\TD\\TD(20).jpg",
        rw: "\\RW\\RW(20).png",
        ls: " \\LS\\LS(20).png",
    },
    "21": {
        name: "The World",
        meaning: "Completion, recognition, fulfillment, triumph, celebration",
        td: "\\TD\\TD(21).jpg",
        rw: "\\RW\\RW(21).png",
        ls: " \\LS\\LS(21).png",
    },
    "22": {
        name: "Ace of Cups",
        meaning: "Happiness, love, intimacy, new emotions, compassion",
        td: "\\TD\\TD(22).jpg",
        rw: "\\RW\\RW(22).png",
        ls: " \\LS\\LS(22).png",
    },
    "23": {
        name: "Two of Cups",
        meaning: "A happy relationship, equality, partnership, attraction, connection",
        td: "\\TD\\TD(23).jpg",
        rw: "\\RW\\RW(23).png",
        ls: " \\LS\\LS(23).png",
    },
    "24": {
        name: "Three of Cups",
        meaning: "Celebrations, friends, indulgence, parties, community",
        td: "\\TD\\TD(24).jpg",
        rw: "\\RW\\RW(24).png",
        ls: " \\LS\\LS(24).png",
    },
    "25": {
        name: "Four of Cups",
        meaning: "A lack of awareness, pessimism, daydreaming, lethargy, reevaluation.",
        td: "\\TD\\TD(25).jpg",
        rw: "\\RW\\RW(25).png",
        ls: " \\LS\\LS(25).png",
    },
    "26": {
        name: "Five of Cups",
        meaning: "Self-plty, guilt, regret, stagnation, depression",
        td: "\\TD\\TD(26).jpg",
        rw: "\\RW\\RW(26).png",
        ls: " \\LS\\LS(26).png",
    },
    "27": {
        name: "Six of Cups",
        meaning: "Nostalgia, old friends, simple joys, sharing, childhood",
        td: "\\TD\\TD(27).jpg",
        rw: "\\RW\\RW(27).png",
        ls: " \\LS\\LS(27).png",
    },
    "28": {
        name: "Seven of Cups",
        meaning: "Daydreaming, fantasy, decisions, wishful thinking, procrastination",
        td: "\\TD\\TD(28).jpg",
        rw: "\\RW\\RW(28).png",
        ls: " \\LS\\LS(28).png",
    },
    "29": {
        name: "Eight of Cups",
        meaning: "Walking away, introspection, escapism, withdrawal, seeking truth",
        td: "\\TD\\TD(29).jpg",
        rw: "\\RW\\RW(29).png",
        ls: " \\LS\\LS(29).png",
    },
    "30": {
        name: "Nine of Cups",
        meaning: "Dreams realized, fulfillment, pleasure, recognition, triumph",
        td: "\\TD\\TD(30).jpg",
        rw: "\\RW\\RW(30).png",
        ls: " \\LS\\LS(30).png",
    },
    "31": {
        name: "Ten of Cups",
        meaning: "Harmony, reunions, security, domestic bliss, found family",
        td: "\\TD\\TD(31).jpg",
        rw: "\\RW\\RW(31).png",
        ls: " \\LS\\LS(31).png",
    },
    "32": {
        name: "Page of Cups",
        meaning: "Youthfulness, idealism, sensitivity, romance, spirituality",
        td: "\\TD\\TD(32).jpg",
        rw: "\\RW\\RW(32).png",
        ls: " \\LS\\LS(32).png",
    },
    "33": {
        name: "Knight of Cups",
        meaning: "Chivalry, affection, imitations, taking action, meaningful gifts",
        td: "\\TD\\TD(33).jpg",
        rw: "\\RW\\RW(33).png",
        ls: " \\LS\\LS(33).png",
    },
    "34": {
        name: "Queen of Cups",
        meaning: "Femininity, warmth, empathy, a counselor, intuition",
        td: "\\TD\\TD(34).jpg",
        rw: "\\RW\\RW(34).png",
        ls: " \\LS\\LS(34).png",
    },
    "35": {
        name: "King of Cups",
        meaning: "Devotion, loyalty, faithfulness, wisdom, generosity",
        td: "\\TD\\TD(35).jpg",
        rw: "\\RW\\RW(35).png",
        ls: " \\LS\\LS(35).png",
    },
    "36": {
        name: "Ace of Wands",
        meaning: "Excitement, creativity, a spark, growth, new beginnings",
        td: "\\TD\\TD(36).jpg",
        rw: "\\RW\\RW(36).png",
        ls: " \\LS\\LS(36).png",
    },
    "37": {
        name: "Two of Wands",
        meaning: "Decisions, travel, business opportunities, future planning, cooperation",
        td: "\\TD\\TD(37).jpg",
        rw: "\\RW\\RW(37).png",
        ls: " \\LS\\LS(37).png",
    },
    "38": {
        name: "Three of Wands",
        meaning: "Self-motivation, freedom, reward, romance",
        td: "\\TD\\TD(38).jpg",
        rw: "\\RW\\RW(38).png",
        ls: " \\LS\\LS(38).png",
    },
    "39": {
        name: "Four of Wands",
        meaning: "Reunion, success, pride, happiness, family",
        td: "\\TD\\TD(39).jpg",
        rw: "\\RW\\RW(39).png",
        ls: " \\LS\\LS(39).png",
    },
    "40": {
        name: "Five of Wands",
        meaning: "Rivalry, opponents, disagreement, competition, clashing egos",
        td: "\\TD\\TD(40).jpg",
        rw: "\\RW\\RW(40).png",
        ls: " \\LS\\LS(40).png",
    },
    "41": {
        name: "Six of Wands",
        meaning: "Victory, praise, achievement, reward, fame",
        td: "\\TD\\TD(41).jpg",
        rw: "\\RW\\RW(41).png",
        ls: " \\LS\\LS(41).png",
    },
    "42": {
        name: "Seven of Wands",
        meaning: "Endurance, attack, fighting for beliefs, perseverance, mounting a defense",
        td: "\\TD\\TD(42).jpg",
        rw: "\\RW\\RW(42).png",
        ls: " \\LS\\LS(42).png",
    },
    "43": {
        name: "Eight of Wands",
        meaning: "Speed, momentum, travel, excitement, results",
        td: "\\TD\\TD(43).jpg",
        rw: "\\RW\\RW(43).png",
        ls: " \\LS\\LS(43).png",
    },
    "44": {
        name: "Nine of Wands",
        meaning: "Fatigue, persistence, gathering strength, wounds, resilience",
        td: "\\TD\\TD(44).jpg",
        rw: "\\RW\\RW(44).png",
        ls: " \\LS\\LS(44).png",
    },
    "45": {
        name: "Ten of Wands",
        meaning: "Overwhelm, stress, obligation, refusing aide, duty",
        td: "\\TD\\TD(45).jpg",
        rw: "\\RW\\RW(45).png",
        ls: " \\LS\\LS(45).png",
    },
    "46": {
        name: "Page of Wands",
        meaning: "Playfulness, charisma, discovery, a rogue, enthusiasm",
        td: "\\TD\\TD(46).jpg",
        rw: "\\RW\\RW(46).png",
        ls: " \\LS\\LS(46).png",
    },
    "47": {
        name: "Knight of Wands",
        meaning: "Adventure, passion, a rebel, a flirt, a hot temper",
        td: "\\TD\\TD(47).jpg",
        rw: "\\RW\\RW(47).png",
        ls: " \\LS\\LS(47).png",
    },
    "48": {
        name: "Queen of Wands",
        meaning: "Optimism, independence, confidence, passion, verve",
        td: "\\TD\\TD(48).jpg",
        rw: "\\RW\\RW(48).png",
        ls: " \\LS\\LS(48).png",
    },
    "49": {
        name: "King of Wands",
        meaning: "Honesty, passion, leadership, charm, flexibility",
        td: "\\TD\\TD(49).jpg",
        rw: "\\RW\\RW(49).png",
        ls: " \\LS\\LS(49).png",
    },
    "50": {
        name: "Ace of Pentacles",
        meaning: "New business, money, investments, abundance, security",
        td: "\\TD\\TD(50).jpg",
        rw: "\\RW\\RW(50).png",
        ls: " \\LS\\LS(50).png",
    },
    "51": {
        name: "Two of Pentacles",
        meaning: "Multitasking, balance, choice, flexibility, prioritization",
        td: "\\TD\\TD(51).jpg",
        rw: "\\RW\\RW(51).png",
        ls: " \\LS\\LS(51).png",
    },
    "52": {
        name: "Three of Pentacles",
        meaning: "Studying, growth, collaboration, success, recognition",
        td: "\\TD\\TD(52).jpg",
        rw: "\\RW\\RW(52).png",
        ls: " \\LS\\LS(52).png",
    },
    "53": {
        name: "Four of Pentacles",
        meaning: "Hoarding, possession, financial stability, materialism, stinginess",
        td: "\\TD\\TD(53).jpg",
        rw: "\\RW\\RW(53).png",
        ls: " \\LS\\LS(53).png",
    },
    "54": {
        name: "Five of Pentacles",
        meaning: "Recession, adversity, isolation, unemployment, ruin",
        td: "\\TD\\TD(54).jpg",
        rw: "\\RW\\RW(54).png",
        ls: " \\LS\\LS(54).png",
    },
    "55": {
        name: "Six of Pentacles",
        meaning: "Generosity, charity, kindness, value, reward",
        td: "\\TD\\TD(55).jpg",
        rw: "\\RW\\RW(55).png",
        ls: " \\LS\\LS(55).png",
    },
    "56": {
        name: "Seven of Pentacles",
        meaning: "Reward, perseverance, decisions, investment, fruition",
        td: "\\TD\\TD(56).jpg",
        rw: "\\RW\\RW(56).png",
        ls: " \\LS\\LS(56).png",
    },
    "57": {
        name: "Eight of Pentacles",
        meaning: "Craftsmanship, commitment, determination, ambition, concentration",
        td: "\\TD\\TD(57).jpg",
        rw: "\\RW\\RW(57).png",
        ls: " \\LS\\LS(57).png",
    },
    "58": {
        name: "Nine of Pentacles",
        meaning: "Independence, prosperity, freedom, maturity, self-discipline",
        td: "\\TD\\TD(58).jpg",
        rw: "\\RW\\RW(58).png",
        ls: " \\LS\\LS(58).png",
    },
    "59": {
        name: "Ten of Pentacles",
        meaning: "Inheritance, ancestry, pensions, settling down, financial stability",
        td: "\\TD\\TD(59).jpg",
        rw: "\\RW\\RW(59).png",
        ls: " \\LS\\LS(59).png",
    },
    "60": {
        name: "Page of Pentacles",
        meaning: "Setting goals, Loyalty, positivity, opportunities, manifestation",
        td: "\\TD\\TD(60).jpg",
        rw: "\\RW\\RW(60).png",
        ls: " \\LS\\LS(60).png",
    },
    "61": {
        name: "Knight of Pentacles",
        meaning: "Ambition, hard work, persistence, being efficient",
        td: "\\TD\\TD(61).jpg",
        rw: "\\RW\\RW(61).png",
        ls: " \\LS\\LS(61).png",
    },
    "62": {
        name: "Queen of Pentacles",
        meaning: "A healer, luxury, being grounded, practicality, movement",
        td: "\\TD\\TD(62).jpg",
        rw: "\\RW\\RW(62).png",
        ls: " \\LS\\LS(62).png",
    },
    "63": {
        name: "King of Pentacles",
        meaning: "Success, dependability, conservatism, strong will, living to work",
        td: "\\TD\\TD(63).jpg",
        rw: "\\RW\\RW(63).png",
        ls: " \\LS\\LS(63).png",
    },
    "64": {
        name: "Ace of Swords",
        meaning: "New projects, truth, assertiveness, creative thinking, clarity",
        td: "\\TD\\TD(64).jpg",
        rw: "\\RW\\RW(64).png",
        ls: " \\LS\\LS(64).png",
    },
    "65": {
        name: "Two of Swords",
        meaning: "Facing fears, a stalemate, denial, opposition, a precarious position",
        td: "\\TD\\TD(65).jpg",
        rw: "\\RW\\RW(65).png",
        ls: " \\LS\\LS(65).png",
    },
    "66": {
        name: "Three of Swords",
        meaning: "Heartbreak, self-harm, sadness, grief, separation.",
        td: "\\TD\\TD(66).jpg",
        rw: "\\RW\\RW(66).png",
        ls: " \\LS\\LS(66).png",
    },
    "67": {
        name: "Four of Swords",
        meaning: "Sanctuary, recouping, meditation, passivity, counseling",
        td: "\\TD\\TD(67).jpg",
        rw: "\\RW\\RW(67).png",
        ls: " \\LS\\LS(67).png",
    },
    "68": {
        name: "Five of Swords",
        meaning: "Surrender, betrayal, bullying, violence, crime",
        td: "\\TD\\TD(68).jpg",
        rw: "\\RW\\RW(68).png",
        ls: " \\LS\\LS(68).png",
    },
    "69": {
        name: "Six of Swords",
        meaning: "Healing, moving forward, stability, escape, journeys",
        td: "\\TD\\TD(69).jpg",
        rw: "\\RW\\RW(69).png",
        ls: " \\LS\\LS(69).png",
    },
    "70": {
        name: "Seven of Swords",
        meaning: "Strategy, cunning, thievery, cheating, manipulation",
        td: "\\TD\\TD(70).jpg",
        rw: "\\RW\\RW(70).png",
        ls: " \\LS\\LS(70).png",
    },
    "71": {
        name: "Eight of Swords",
        meaning: "Anxiety, victimhood, feeling trapped, paralysis, crisis",
        td: "\\TD\\TD(71).jpg",
        rw: "\\RW\\RW(71).png",
        ls: " \\LS\\LS(71).png",
    },
    "72": {
        name: "Nine of Swords",
        meaning: "Anxiety, terror, nightmares, obsession, insomnia",
        td: "\\TD\\TD(72).jpg",
        rw: "\\RW\\RW(72).png",
        ls: " \\LS\\LS(72).png",
    },
    "73": {
        name: "Ten of Swords",
        meaning: "Bitterness, betrayal, rock bottom, martyrdom, severing ties",
        td: "\\TD\\TD(73).jpg",
        rw: "\\RW\\RW(73).png",
        ls: " \\LS\\LS(73).png",
    },
    "74": {
        name: "Page of Swords",
        meaning: "Talkativeness, energy, thoughtfulness, curiosity, truthfulness",
        td: "\\TD\\TD(74).jpg",
        rw: "\\RW\\RW(74).png",
        ls: " \\LS\\LS(74).png",
    },
    "75": {
        name: "Knight of Swords",
        meaning: "Intellect, bravery, confidence, being action-oriented",
        td: "\\TD\\TD(75).jpg",
        rw: "\\RW\\RW(75).png",
        ls: " \\LS\\LS(75).png",
    },
    "76": {
        name: "Queen of Swords",
        meaning: "Protection, meaningful criticism, tough love, skepticism, intelligence",
        td: "\\TD\\TD(76).jpg",
        rw: "\\RW\\RW(76).png",
        ls: " \\LS\\LS(76).png",
    },
    "77": {
        name: "King of Swords",
        meaning: "Authority, structure, logic, self-discipline, loyalty",
        td: "\\TD\\TD(77).jpg",
        rw: "\\RW\\RW(77).png",
        ls: " \\LS\\LS(77).png",
    },
};
