// Cards storage
const cards = {
    "0": {
        name: "The Fool",
        meaning: "Beginnings, possibilities, impulsiveness, innocence, a free spirit",
        td: "https://i.imgur.com/09MyMit.jpg",
        rw: "https://i.imgur.com/LnbK1Xy.png",
        ls: " https://i.imgur.com/CZd6eUr.png",
    },
    "1": {
        name: "The Magician",
        meaning: "Originality, self-confidence, skill, a breakthrough, resourcefulness",
        td: "https://i.imgur.com/UAV1i6g.jpg",
        rw: "https://i.imgur.com/wErnh3L.png",
        ls: " https://i.imgur.com/47fi4Wv.png",
    },
    "2": {
        name: "The High Priestess",
        meaning: "Wisdom, intuition, dreams, meandering, an enigma",
        td: "https://i.imgur.com/P87ALOB.jpg",
        rw: "https://i.imgur.com/hUXWTOB.png",
        ls: " https://i.imgur.com/V4dfy3S.png",
    },
    "3": {
        name: "The Empress",
        meaning: "Fertility, nurturing, accomplishment, nature, abundance",
        td: "https://i.imgur.com/MGDE1Kn.jpg",
        rw: "https://i.imgur.com/J97pITt.png",
        ls: " https://i.imgur.com/sq7T4XJ.png",
    },
    "4": {
        name: "The Emperor",
        meaning: "Stability, leadership, bravery, bold action, structure",
        td: "https://i.imgur.com/t4JH8Bo.jpg",
        rw: "https://i.imgur.com/BCpvtif.png",
        ls: " https://i.imgur.com/AKeC0ak.png",
    },
    "5": {
        name: "The Hierophant",
        meaning: "Conformity, compassion, social approval, tradition, legacy",
        td: "https://i.imgur.com/65KylCu.jpg",
        rw: "https://i.imgur.com/CeylKWx.png",
        ls: " https://i.imgur.com/mJyXmZb.png",
    },
    "6": {
        name: "The Lovers",
        meaning: "Love, harmony, trust, a leap of faith, choice",
        td: "https://i.imgur.com/ymiH2n2.png",
        rw: "https://i.imgur.com/K8JKMUz.png",
        ls: " https://i.imgur.com/S3uyFPg.png",
    },
    "7": {
        name: "The Chariot",
        meaning: "A journey, perseverance, rushed decisions, vengeance, victory",
        td: "https://i.imgur.com/QSNxQYd.jpg",
        rw: "https://i.imgur.com/b9HyHn6.png",
        ls: " https://i.imgur.com/MgimyUv.png",
    },
    "8": {
        name: "Strength",
        meaning: "Courage, conviction, control, determination, patience",
        td: "https://i.imgur.com/432WnbQ.jpg",
        rw: "https://i.imgur.com/XHxDTCa.png",
        ls: " https://i.imgur.com/eEPR2xR.png",
    },
    "9": {
        name: "The Hermit",
        meaning: "Introspection, withdrawal, prudence, insight, meditation",
        td: "https://i.imgur.com/1WXunMl.png",
        rw: "https://i.imgur.com/vYLEQDf.png",
        ls: " https://i.imgur.com/D5fic4L.png",
    },
    "10": {
        name: "Wheel of Fortune",
        meaning: "Fortune, an unexpected windfall, karma, destiny, cycles",
        td: "https://i.imgur.com/k18qAXe.jpg",
        rw: "https://i.imgur.com/5VejAUV.png",
        ls: " https://i.imgur.com/Loc2OE1.png",
    },
    "11": {
        name: "Justice",
        meaning: "Harmony, balance, equality, virtue, honor",
        td: "https://i.imgur.com/0XdLbna.jpg",
        rw: "https://i.imgur.com/tCfPUNy.png",
        ls: " https://i.imgur.com/gO3TUmY.png",
    },
    "12": {
        name: "The Hanged Man",
        meaning: "Suspension, restriction, sacrifice, readjustment, improvement",
        td: "https://i.imgur.com/toVCJNG.jpg",
        rw: "https://i.imgur.com/3JTKNZM.png",
        ls: " https://i.imgur.com/f3NlgLX.png",
    },
    "13": {
        name: "Death",
        meaning: "Metamorphosis, evolution, loss, transition, change",
        td: "https://i.imgur.com/PwHhoe6.png",
        rw: "https://i.imgur.com/o3H0rkH.png",
        ls: " https://i.imgur.com/95WTrzI.png",
    },
    "14": {
        name: "Temperance",
        meaning: "Moderation, harmony, purpose, good influence, reconciliation",
        td: "https://i.imgur.com/gfikuqp.png",
        rw: "https://i.imgur.com/S6JmgqN.png",
        ls: " https://i.imgur.com/vvEbQbr.png",
    },
    "15": {
        name: "The Devil",
        meaning: "Greed, controversy, violence, strange experiences, addiction",
        td: "https://i.imgur.com/9x7AUZU.png",
        rw: "https://i.imgur.com/l4jyYbb.png",
        ls: " https://i.imgur.com/V2BBCza.png",
    },
    "16": {
        name: "The Tower",
        meaning: "Massive change, upheaval, catastrophe, rebuilding, revelation",
        td: "https://i.imgur.com/oZRNMEb.jpg",
        rw: "https://i.imgur.com/L33YcNm.png",
        ls: " https://i.imgur.com/n0ukMTo.png",
    },
    "17": {
        name: "The Star",
        meaning: "Hope, serenity, inspiration , insight, spirituality",
        td: "https://i.imgur.com/4rrRK1x.png",
        rw: "https://i.imgur.com/2lGgbla.png",
        ls: " https://i.imgur.com/XFVTNCG.png",
    },
    "18": {
        name: "The Moon",
        meaning: "Trickery, melancholy, anguish , illusion, insecurity",
        td: "https://i.imgur.com/ndc5Bal.png",
        rw: "https://i.imgur.com/XKBhYF1.png",
        ls: " https://i.imgur.com/7EVxbet.png",
    },
    "19": {
        name: "The Sun",
        meaning: "Satisfaction, accomplishment, joy, luck, vitality",
        td: "https://i.imgur.com/5E5YOtX.jpg",
        rw: "https://i.imgur.com/UQEfTAf.png",
        ls: " https://i.imgur.com/txIrEL8.png",
    },
    "20": {
        name: "Judgement",
        meaning: "Improvement, forgiveness, a change of perspective, absolution, rebirth",
        td: "https://i.imgur.com/KIDUEgw.png",
        rw: "https://i.imgur.com/qfrcrNf.png",
        ls: " https://i.imgur.com/oA6EnW0.png",
    },
    "21": {
        name: "The World",
        meaning: "Completion, recognition, fulfillment, triumph, celebration",
        td: "https://i.imgur.com/jdF72av.jpg",
        rw: "https://i.imgur.com/ciCvCYJ.png",
        ls: " https://i.imgur.com/kkq6o2Z.png",
    },
    "22": {
        name: "Ace of Cups",
        meaning: "Happiness, love, intimacy, new emotions, compassion",
        td: "https://i.imgur.com/TpMssPj.jpg",
        rw: "https://i.imgur.com/PtOSjTs.png",
        ls: " https://i.imgur.com/shJI613.png",
    },
    "23": {
        name: "Two of Cups",
        meaning: "A happy relationship, equality, partnership, attraction, connection",
        td: "https://i.imgur.com/quEAzd0.jpg",
        rw: "https://i.imgur.com/ZJtmOhG.png",
        ls: " https://i.imgur.com/P0FmeI1.png",
    },
    "24": {
        name: "Three of Cups",
        meaning: "Celebrations, friends, indulgence, parties, community",
        td: "https://i.imgur.com/hsmWShL.jpg",
        rw: "https://i.imgur.com/a4btiik.png",
        ls: " https://i.imgur.com/7DTTLhZ.png",
    },
    "25": {
        name: "Four of Cups",
        meaning: "A lack of awareness, pessimism, daydreaming, lethargy, reevaluation",
        td: "https://i.imgur.com/lyn3uEc.jpg",
        rw: "https://i.imgur.com/PDbIzc6.png",
        ls: " https://i.imgur.com/vouikR1.png",
    },
    "26": {
        name: "Five of Cups",
        meaning: "Self-plty, guilt, regret, stagnation, depression",
        td: "https://i.imgur.com/5WRyPgM.jpg",
        rw: "https://i.imgur.com/1P9ZhBj.png",
        ls: " https://i.imgur.com/86Ogbj3.png",
    },
    "27": {
        name: "Six of Cups",
        meaning: "Nostalgia, old friends, simple joys, sharing, childhood",
        td: "https://i.imgur.com/UMQJvUR.jpg",
        rw: "https://i.imgur.com/EvMeRHX.png",
        ls: " https://i.imgur.com/kJzqjIg.png",
    },
    "28": {
        name: "Seven of Cups",
        meaning: "Daydreaming, fantasy, decisions, wishful thinking, procrastination",
        td: "https://i.imgur.com/6LFBdC3.jpg",
        rw: "https://i.imgur.com/ooJnVNW.png",
        ls: " https://i.imgur.com/5HT0xr3.png",
    },
    "29": {
        name: "Eight of Cups",
        meaning: "Walking away, introspection, escapism, withdrawal, seeking truth",
        td: "https://i.imgur.com/jqvu6o8.jpg",
        rw: "https://i.imgur.com/EVjPLKq.png",
        ls: " https://i.imgur.com/g5nFwRz.png",
    },
    "30": {
        name: "Nine of Cups",
        meaning: "Dreams realized, fulfillment, pleasure, recognition, triumph",
        td: "https://i.imgur.com/THoDigg.jpg",
        rw: "https://i.imgur.com/MifAwKL.png",
        ls: " https://i.imgur.com/zXTOqxC.png",
    },
    "31": {
        name: "Ten of Cups",
        meaning: "Harmony, reunions, security, domestic bliss, found family",
        td: "https://i.imgur.com/qy6hOwg.jpg",
        rw: "https://i.imgur.com/CCQpYoa.png",
        ls: " https://i.imgur.com/VJqnvSv.png",
    },
    "32": {
        name: "Page of Cups",
        meaning: "Youthfulness, idealism, sensitivity, romance, spirituality",
        td: "https://i.imgur.com/jDXubxJ.jpg",
        rw: "https://i.imgur.com/MKgRKbM.png",
        ls: " https://i.imgur.com/bTBe8l2.png",
    },
    "33": {
        name: "Knight of Cups",
        meaning: "Chivalry, affection, imitations, taking action, meaningful gifts",
        td: "https://i.imgur.com/ukHaETc.jpg",
        rw: "https://i.imgur.com/p1w8TPA.png",
        ls: " https://i.imgur.com/ejzRTbY.png",
    },
    "34": {
        name: "Queen of Cups",
        meaning: "Femininity, warmth, empathy, a counselor, intuition",
        td: "https://i.imgur.com/fWl8par.jpg",
        rw: "https://i.imgur.com/PTlkHfl.png",
        ls: " https://i.imgur.com/jY1shOv.png",
    },
    "35": {
        name: "King of Cups",
        meaning: "Devotion, loyalty, faithfulness, wisdom, generosity",
        td: "https://i.imgur.com/JsnoAjy.png",
        rw: "https://i.imgur.com/QK1D3gM.png",
        ls: " https://i.imgur.com/ZOxkm12.png",
    },
    "36": {
        name: "Ace of Wands",
        meaning: "Excitement, creativity, a spark, growth, new beginnings",
        td: "https://i.imgur.com/GydND6E.jpg",
        rw: "https://i.imgur.com/mChfZ4l.png",
        ls: " https://i.imgur.com/0ehHcI3.png",
    },
    "37": {
        name: "Two of Wands",
        meaning: "Decisions, travel, business opportunities, future planning, cooperation",
        td: "https://i.imgur.com/9aA4Ylh.jpg",
        rw: "https://i.imgur.com/kV7M3oF.png",
        ls: " https://i.imgur.com/e8M0OUt.png",
    },
    "38": {
        name: "Three of Wands",
        meaning: "Self-motivation, freedom, reward, romance",
        td: "https://i.imgur.com/7iLxqY6.png",
        rw: "https://i.imgur.com/Sm5VTwn.png",
        ls: " https://i.imgur.com/bFkQkPX.png",
    },
    "39": {
        name: "Four of Wands",
        meaning: "Reunion, success, pride, happiness, family",
        td: "https://i.imgur.com/p4c6ZTH.png",
        rw: "https://i.imgur.com/8IeQ88W.png",
        ls: " https://i.imgur.com/qcrvSQh.png",
    },
    "40": {
        name: "Five of Wands",
        meaning: "Rivalry, opponents, disagreement, competition, clashing egos",
        td: "https://i.imgur.com/l56r3Um.png",
        rw: "https://i.imgur.com/VV9Dguk.png",
        ls: " https://i.imgur.com/tt0TxkK.png",
    },
    "41": {
        name: "Six of Wands",
        meaning: "Victory, praise, achievement, reward, fame",
        td: "https://i.imgur.com/isof0Q9.jpg",
        rw: "https://i.imgur.com/k20cJhA.png",
        ls: " https://i.imgur.com/iDJCGUG.png",
    },
    "42": {
        name: "Seven of Wands",
        meaning: "Endurance, attack, fighting for beliefs, perseverance, mounting a defense",
        td: "https://i.imgur.com/sJSODPE.png",
        rw: "https://i.imgur.com/2JN9WUk.png",
        ls: " https://i.imgur.com/893Ioxz.png",
    },
    "43": {
        name: "Eight of Wands",
        meaning: "Speed, momentum, travel, excitement, results",
        td: "https://i.imgur.com/2uWk4wV.jpg",
        rw: "https://i.imgur.com/R1CyWrp.png",
        ls: " https://i.imgur.com/ISfKnmb.png",
    },
    "44": {
        name: "Nine of Wands",
        meaning: "Fatigue, persistence, gathering strength, wounds, resilience",
        td: "https://i.imgur.com/9SYZ4qE.jpg",
        rw: "https://i.imgur.com/fePM3YN.png",
        ls: " https://i.imgur.com/Nldsyjy.png",
    },
    "45": {
        name: "Ten of Wands",
        meaning: "Overwhelm, stress, obligation, refusing aide, duty",
        td: "https://i.imgur.com/pHkuRV1.png",
        rw: "https://i.imgur.com/KJv9EA3.png",
        ls: " https://i.imgur.com/GX89t6m.png",
    },
    "46": {
        name: "Page of Wands",
        meaning: "Playfulness, charisma, discovery, a rogue, enthusiasm",
        td: "https://i.imgur.com/iIqOAYA.png",
        rw: "https://i.imgur.com/BIMbaz2.png",
        ls: " https://i.imgur.com/CivScYG.png",
    },
    "47": {
        name: "Knight of Wands",
        meaning: "Adventure, passion, a rebel, a flirt, a hot temper",
        td: "https://i.imgur.com/pXCpwhj.jpg",
        rw: "https://i.imgur.com/GMUeMvQ.png",
        ls: " https://i.imgur.com/iCzwzVx.png",
    },
    "48": {
        name: "Queen of Wands",
        meaning: "Optimism, independence, confidence, passion, verve",
        td: "https://i.imgur.com/o5EnO8g.png",
        rw: "https://i.imgur.com/Vj8f9j7.png",
        ls: " https://i.imgur.com/Qsqmmk2.png",
    },
    "49": {
        name: "King of Wands",
        meaning: "Honesty, passion, leadership, charm, flexibility",
        td: "https://i.imgur.com/JMCg9gL.png",
        rw: "https://i.imgur.com/hwHw3pm.png",
        ls: " https://i.imgur.com/koxwmnY.png",
    },
    "50": {
        name: "Ace of Pentacles",
        meaning: "New business, money, investments, abundance, security",
        td: "https://i.imgur.com/i5XJww8.jpg",
        rw: "https://i.imgur.com/EhLS4Ut.png",
        ls: " https://i.imgur.com/sdcH4hh.png",
    },
    "51": {
        name: "Two of Pentacles",
        meaning: "Multitasking, balance, choice, flexibility, prioritization",
        td: "https://i.imgur.com/aL4w7pY.jpg",
        rw: "https://i.imgur.com/4cnwJQL.png",
        ls: " https://i.imgur.com/1YF4pcU.png",
    },
    "52": {
        name: "Three of Pentacles",
        meaning: "Studying, growth, collaboration, success, recognition",
        td: "https://i.imgur.com/HDwn5QX.jpg",
        rw: "https://i.imgur.com/OIlHiQ9.png",
        ls: " https://i.imgur.com/mAeEcdA.png",
    },
    "53": {
        name: "Four of Pentacles",
        meaning: "Hoarding, possession, financial stability, materialism, stinginess",
        td: "https://i.imgur.com/xlNshbL.jpg",
        rw: "https://i.imgur.com/wev6s6Y.png",
        ls: " https://i.imgur.com/ReyBBpU.png",
    },
    "54": {
        name: "Five of Pentacles",
        meaning: "Recession, adversity, isolation, unemployment, ruin",
        td: "https://i.imgur.com/BpgVHvb.png",
        rw: "https://i.imgur.com/lJeAWFH.png",
        ls: " https://i.imgur.com/NIE86k0.png",
    },
    "55": {
        name: "Six of Pentacles",
        meaning: "Generosity, charity, kindness, value, reward",
        td: "https://i.imgur.com/j07ox6V.jpg",
        rw: "https://i.imgur.com/LzODMUw.png",
        ls: " https://i.imgur.com/fgsUWnz.png",
    },
    "56": {
        name: "Seven of Pentacles",
        meaning: "Reward, perseverance, decisions, investment, fruition",
        td: "https://i.imgur.com/reVgkCA.png",
        rw: "https://i.imgur.com/aDbIfWA.png",
        ls: " https://i.imgur.com/3vUxLB2.png",
    },
    "57": {
        name: "Eight of Pentacles",
        meaning: "Craftsmanship, commitment, determination, ambition, concentration",
        td: "https://i.imgur.com/lKwIS1K.jpg",
        rw: "https://i.imgur.com/bhnZcre.png",
        ls: " https://i.imgur.com/sr5RsYI.png",
    },
    "58": {
        name: "Nine of Pentacles",
        meaning: "Independence, prosperity, freedom, maturity, self-discipline",
        td: "https://i.imgur.com/xAQHOy8.jpg",
        rw: "https://i.imgur.com/03pm582.png",
        ls: " https://i.imgur.com/W2v89WT.png",
    },
    "59": {
        name: "Ten of Pentacles",
        meaning: "Inheritance, ancestry, pensions, settling down, financial stability",
        td: "https://i.imgur.com/XyoZPYy.jpg",
        rw: "https://i.imgur.com/YzWCxHQ.png",
        ls: " https://i.imgur.com/0sCnJQD.png",
    },
    "60": {
        name: "Page of Pentacles",
        meaning: "Setting goals, Loyalty, positivity, opportunities, manifestation",
        td: "https://i.imgur.com/lD8waBo.jpg",
        rw: "https://i.imgur.com/GCOyT76.png",
        ls: " https://i.imgur.com/x84LKkH.png",
    },
    "61": {
        name: "Knight of Pentacles",
        meaning: "Ambition, hard work, persistence, being efficient",
        td: "https://i.imgur.com/4BZgNea.jpg",
        rw: "https://i.imgur.com/I4zuC1o.png",
        ls: " https://i.imgur.com/1aBWJde.png",
    },
    "62": {
        name: "Queen of Pentacles",
        meaning: "A healer, luxury, being grounded, practicality, movement",
        td: "https://i.imgur.com/6tXjGxA.jpg",
        rw: "https://i.imgur.com/mh1QdJw.png",
        ls: " https://i.imgur.com/THrzGIX.png",
    },
    "63": {
        name: "King of Pentacles",
        meaning: "Success, dependability, conservatism, strong will, living to work",
        td: "https://i.imgur.com/JL4KeTe.jpg",
        rw: "https://i.imgur.com/O8z2Igw.png",
        ls: " https://i.imgur.com/qQJPlEu.png",
    },
    "64": {
        name: "Ace of Swords",
        meaning: "New projects, truth, assertiveness, creative thinking, clarity",
        td: "https://i.imgur.com/rH46Wzr.jpg",
        rw: "https://i.imgur.com/ybhPg1W.png",
        ls: " https://i.imgur.com/Zj8z1zr.png",
    },
    "65": {
        name: "Two of Swords",
        meaning: "Facing fears, a stalemate, denial, opposition, a precarious position",
        td: "https://i.imgur.com/4vz8dX9.jpg",
        rw: "https://i.imgur.com/uJNEt3V.png",
        ls: " https://i.imgur.com/6XiAaf5.png",
    },
    "66": {
        name: "Three of Swords",
        meaning: "Heartbreak, self-harm, sadness, grief, separation.",
        td: "https://i.imgur.com/cZvXaov.png",
        rw: "https://i.imgur.com/rh767Fw.png",
        ls: " https://i.imgur.com/xtvKsq8.png",
    },
    "67": {
        name: "Four of Swords",
        meaning: "Sanctuary, recouping, meditation, passivity, counseling",
        td: "https://i.imgur.com/BWuJ7O5.png",
        rw: "https://i.imgur.com/MtHA1fr.png",
        ls: " https://i.imgur.com/DJJJROJ.png",
    },
    "68": {
        name: "Five of Swords",
        meaning: "Surrender, betrayal, bullying, violence, crime",
        td: "https://i.imgur.com/VTZDbXv.png",
        rw: "https://i.imgur.com/ySyLGKk.png",
        ls: " https://i.imgur.com/sZEI1na.png",
    },
    "69": {
        name: "Six of Swords",
        meaning: "Healing, moving forward, stability, escape, journeys",
        td: "https://i.imgur.com/G1P4nS3.jpg",
        rw: "https://i.imgur.com/pIiRcC1.png",
        ls: " https://i.imgur.com/l83D6eL.png",
    },
    "70": {
        name: "Seven of Swords",
        meaning: "Strategy, cunning, thievery, cheating, manipulation",
        td: "https://i.imgur.com/DHRLLVM.jpg",
        rw: "https://i.imgur.com/thlnjyN.png",
        ls: " https://i.imgur.com/DEqFNNd.png",
    },
    "71": {
        name: "Eight of Swords",
        meaning: "Anxiety, victimhood, feeling trapped, paralysis, crisis",
        td: "https://i.imgur.com/6tFLMGx.jpg",
        rw: "https://i.imgur.com/CBlTSJq.png",
        ls: " https://i.imgur.com/tJjFCbv.png",
    },
    "72": {
        name: "Nine of Swords",
        meaning: "Anxiety, terror, nightmares, obsession, insomnia",
        td: "https://i.imgur.com/H9Wf9Ww.jpg",
        rw: "https://i.imgur.com/N3r7j45.png",
        ls: " https://i.imgur.com/2R3GZZE.png",
    },
    "73": {
        name: "Ten of Swords",
        meaning: "Bitterness, betrayal, rock bottom, martyrdom, severing ties",
        td: "https://i.imgur.com/RkTS9g1.png",
        rw: "https://i.imgur.com/rOT71ra.png",
        ls: " https://i.imgur.com/OEqxdLp.png",
    },
    "74": {
        name: "Page of Swords",
        meaning: "Talkativeness, energy, thoughtfulness, curiosity, truthfulness",
        td: "https://i.imgur.com/18JBQkl.jpg",
        rw: "https://i.imgur.com/mEGOfNu.png",
        ls: " https://i.imgur.com/Z2ajWuS.png",
    },
    "75": {
        name: "Knight of Swords",
        meaning: "Intellect, bravery, confidence, being action-oriented",
        td: "https://i.imgur.com/YW8nzcR.jpg",
        rw: "https://i.imgur.com/IrTfK9G.png",
        ls: " https://i.imgur.com/yIZOxgE.png",
    },
    "76": {
        name: "Queen of Swords",
        meaning: "Protection, meaningful criticism, tough love, skepticism, intelligence",
        td: "https://i.imgur.com/Diw8ZOF.jpg",
        rw: "https://i.imgur.com/CxIGN2k.png",
        ls: " https://i.imgur.com/V9c1q2k.png",
    },
    "77": {
        name: "King of Swords",
        meaning: "Authority, structure, logic, self-discipline, loyalty",
        td: "https://i.imgur.com/bb6odpE.png",
        rw: "https://i.imgur.com/rQ7nSkK.png",
        ls: " https://i.imgur.com/cS3MYQU.png",
    },
    };